=== ibrasow5/Gestion_films/exo2.dtd
<!ELEMENT programme (liste_films)>
<!ELEMENT liste_films (film*)>
<!ELEMENT film (titre, duree, genre, realisateur, acteurs, annee_production, langue, paragraphe, liste_horaires)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT duree (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT realisateur (#PCDATA)>
<!ELEMENT acteurs (acteur*)>
<!ELEMENT acteur (nom, prenom)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT annee_production (#PCDATA)>
<!ELEMENT langue (#PCDATA)>
<!ELEMENT paragraphe (#PCDATA)>
<!ELEMENT liste_horaires (horaires*)>
<!ELEMENT horaires (jour, heure)>
<!ELEMENT jour (#PCDATA)>
<!ELEMENT heure (#PCDATA)>

=== ibrasow5/Gestion_films/exo2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE programme SYSTEM "exo2.dtd">
<programme>
    <liste_films>
        <film>
            <titre>Les Brigades du Tigre</titre>
            <duree>2h05</duree>
            <genre>Policier</genre>
            <realisateur>Jerome Cornuau</realisateur>
            <acteurs>
                <acteur>
                    <nom>Cornillac</nom>
                    <prenom>C.</prenom>
                </acteur>
                <acteur>
                    <nom>Kruger</nom>
                    <prenom>D.</prenom>
                </acteur>
            </acteurs>
            <annee_production>2005</annee_production>
            <langue>VF(Francais)</langue>
            <paragraphe>
                Les aventures du commissaire Valentin et des inspecteurs Terrasson et Pujol, 
                membres des Brigades mobiles, corps spécial de la police française créé avant 
                la Première Guerre mondiale
            </paragraphe>
            <liste_horaires>
                <horaires>
                    <jour>Lundi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Mardi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Mercredi</jour>
                    <heure>14:00|16:40|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Jeudi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Vendredi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Samedi</jour>
                    <heure>14:00|16:40|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Dimanche</jour>
                    <heure>10:20|14:00|16:40|20:20</heure>
                </horaires>
            </liste_horaires>
        </film>

        <film>
            <titre>Harry Potter à l'école des sorciers</titre>
            <duree>1h58</duree>
            <genre>Fantastique</genre>
            <realisateur>Chris Columbus</realisateur>
            <acteurs>
                <acteur>
                    <nom>Radcliffe</nom>
                    <prenom>Daniel</prenom>
                </acteur>
                <acteur>
                    <nom>Grint</nom>
                    <prenom>Rupert</prenom>
                </acteur>
            </acteurs>
            <annee_production>2001</annee_production>
            <langue>VF(Francais)</langue>
            <paragraphe>
                Harry Potter découvre qu'il est un sorcier et entame sa première année à l'école de sorcellerie de Poudlard, où il se fait des amis et des ennemis et découvre un secret important sur son passé.
            </paragraphe>
            <liste_horaires>
                <horaires>
                    <jour>Lundi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Mardi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Mercredi</jour>
                    <heure>14:00|16:40|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Jeudi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Vendredi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Samedi</jour>
                    <heure>14:00|16:40|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Dimanche</jour>
                    <heure>10:20|14:00|16:40|20:20</heure>
                </horaires>
            </liste_horaires>
        </film>

        <film>
            <titre>Harry Potter et la Chambre des Secrets</titre>
            <duree>2h06</duree>
            <genre>Fantastique</genre>
            <realisateur>Chris Columbus</realisateur>
            <acteurs>
                <acteur>
                    <nom>Radcliffe</nom>
                    <prenom>Daniel</prenom>
                </acteur>
                <acteur>
                    <nom>Grint</nom>
                    <prenom>Rupert</prenom>
                </acteur>
            </acteurs>
            <annee_production>2002</annee_production>
            <langue>VF(Francais)</langue>
            <paragraphe>
                Lors de sa deuxième année à Poudlard, Harry Potter découvre un complot dangereux impliquant une mystérieuse chambre secrète et un héritier de Serpentard.
            </paragraphe>
            <liste_horaires>
                <horaires>
                    <jour>Lundi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Mardi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Mercredi</jour>
                    <heure>14:00|16:40|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Jeudi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Vendredi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Samedi</jour>
                    <heure>14:00|16:40|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Dimanche</jour>
                    <heure>10:20|14:00|16:40|20:20</heure>
                </horaires>
            </liste_horaires>
        </film>

        <film>
            <titre>Harry Potter et le Prisonnier d'Azkaban</titre>
            <duree>2h06</duree>
            <genre>Fantastique</genre>
            <realisateur>Chris Columbus</realisateur>
            <acteurs>
                <acteur>
                    <nom>Radcliffe</nom>
                    <prenom>Daniel</prenom>
                </acteur>
                <acteur>
                    <nom>Grint</nom>
                    <prenom>Rupert</prenom>
                </acteur>
            </acteurs>
            <annee_production>2004</annee_production>
            <langue>VF(Francais)</langue>
            <paragraphe>
                En troisième année, Harry Potter apprend l'évasion de Sirius Black, un dangereux criminel qui semble avoir des liens personnels avec lui.
            </paragraphe>
            <liste_horaires>
                <horaires>
                    <jour>Lundi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Mardi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Mercredi</jour>
                    <heure>14:00|16:40|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Jeudi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Vendredi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Samedi</jour>
                    <heure>14:00|16:40|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Dimanche</jour>
                    <heure>10:20|14:00|16:40|20:20</heure>
                </horaires>
            </liste_horaires>
        </film>

        <film>
            <titre>Harry Potter et le Prince de Sang-Mêlé</titre>
            <duree>2h06</duree>
            <genre>Fantastique</genre>
            <realisateur>Chris Columbus</realisateur>
            <acteurs>
                <acteur>
                    <nom>Radcliffe</nom>
                    <prenom>Daniel</prenom>
                </acteur>
                <acteur>
                    <nom>Grint</nom>
                    <prenom>Rupert</prenom>
                </acteur>
            </acteurs>
            <annee_production>2009</annee_production>
            <langue>VF(Francais)</langue>
            <paragraphe>
                Alors que Voldemort resserre son emprise à la fois sur le monde des Moldus et celui des sorciers, Harry et Dumbledore travaillent ensemble pour trouver les moyens de vaincre le Seigneur des Ténèbres. Entre-temps, des sentiments naissent entre certains élèves de Poudlard, et le danger devient omniprésent dans la vie de Harry.
            </paragraphe>
            <liste_horaires>
                <horaires>
                    <jour>Lundi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Mardi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Mercredi</jour>
                    <heure>14:00|16:40|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Jeudi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Vendredi</jour>
                    <heure>14:00|19:40|22:10</heure>
                </horaires>
                <horaires>
                    <jour>Samedi</jour>
                    <heure>14:00|16:40|19:40|22:10</heure>
                </horaires>
